# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ...harness.v1 import harness_pb2 as sondera_dot_harness_dot_v1_dot_harness__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sondera/harness/v1/harness_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarnessServiceStub(object):
    """Agent governance API for registration, trajectory management, and policy enforcement.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/RegisterAgent',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/GetAgent',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.CreateTrajectory = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/CreateTrajectory',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryResponse.FromString,
                _registered_method=True)
        self.AddTrajectoryStep = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/AddTrajectoryStep',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepResponse.FromString,
                _registered_method=True)
        self.UpdateTrajectoryStatus = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/UpdateTrajectoryStatus',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusResponse.FromString,
                _registered_method=True)
        self.GetTrajectory = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/GetTrajectory',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryResponse.FromString,
                _registered_method=True)
        self.ListTrajectories = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/ListTrajectories',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/ListAgents',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.AnalyzeTrajectories = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/AnalyzeTrajectories',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesResponse.FromString,
                _registered_method=True)
        self.ListAdjudications = channel.unary_unary(
                '/sondera.harness.v1.HarnessService/ListAdjudications',
                request_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsRequest.SerializeToString,
                response_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsResponse.FromString,
                _registered_method=True)


class HarnessServiceServicer(object):
    """Agent governance API for registration, trajectory management, and policy enforcement.
    """

    def RegisterAgent(self, request, context):
        """Registers a new AI agent. Name must be unique within provider namespace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Retrieves an agent by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTrajectory(self, request, context):
        """Creates a new conversation trajectory for an agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTrajectoryStep(self, request, context):
        """Adds a step to a trajectory with real-time adjudication.
        Runs guardrails, evaluates policies, and returns the decision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrajectoryStatus(self, request, context):
        """Updates trajectory status (running, completed, suspended, failed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrajectory(self, request, context):
        """Retrieves a trajectory with its adjudicated steps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrajectories(self, request, context):
        """Lists trajectories for an agent with pagination and status filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Lists registered agents with pagination and optional provider filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTrajectories(self, request, context):
        """Computes analytics for trajectories. Specify desired analytics or omit for all.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAdjudications(self, request, context):
        """Lists adjudicated steps with optional agent filtering and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentResponse.SerializeToString,
            ),
            'CreateTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrajectory,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryResponse.SerializeToString,
            ),
            'AddTrajectoryStep': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTrajectoryStep,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepResponse.SerializeToString,
            ),
            'UpdateTrajectoryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrajectoryStatus,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusResponse.SerializeToString,
            ),
            'GetTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrajectory,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryResponse.SerializeToString,
            ),
            'ListTrajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrajectories,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsResponse.SerializeToString,
            ),
            'AnalyzeTrajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTrajectories,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesResponse.SerializeToString,
            ),
            'ListAdjudications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAdjudications,
                    request_deserializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsRequest.FromString,
                    response_serializer=sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sondera.harness.v1.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sondera.harness.v1.HarnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HarnessService(object):
    """Agent governance API for registration, trajectory management, and policy enforcement.
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/RegisterAgent',
            sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/GetAgent',
            sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/CreateTrajectory',
            sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.CreateTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTrajectoryStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/AddTrajectoryStep',
            sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.AddTrajectoryStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrajectoryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/UpdateTrajectoryStatus',
            sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.UpdateTrajectoryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/GetTrajectory',
            sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.GetTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/ListTrajectories',
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/ListAgents',
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTrajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/AnalyzeTrajectories',
            sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.AnalyzeTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAdjudications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sondera.harness.v1.HarnessService/ListAdjudications',
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsRequest.SerializeToString,
            sondera_dot_harness_dot_v1_dot_harness__pb2.ListAdjudicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
